In [ ]:
# kp1: np.meshgrid
# meshgrid 用于从x和y产生网格，生成的矩阵A和B大小相同，size为size(y)*size(x)

import numpy as np

x = np.array([0, 1, 2])
y = np.array([3, 4])

A, B = np.meshgrid(x, y)

print(A)
print(B)

[[0 1 2]
 [0 1 2]]
[[3 3 3]
 [4 4 4]]


In [3]:
# kp2: 
# np.c_：按column来组合array
# np.r_： 按row来组合array

import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.c_[a, b])
print(np.r_[a,b])
print(np.c_[a, [0, 0, 0], b])

[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 0 4]
 [2 0 5]
 [3 0 6]]
